name: CI Lint

on:
  pull_request:
    # path:
    #   - "src/**"

permissions:
  contents: read
  checks: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history

      - name: Super-Linter
        # uses: super-linter/super-linter@b92721f792f381cedc002ecdbb9847a15ece5bb8
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          OUTPUT_FOLDER: super_linter_report
          OUTPUT_DETAILS: detailed
          # VALIDATE_ALL_CODEBASE: false  # only lint changed files
